#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
扫描知识库根目录下的一级子文件夹，收集 .md / .html 文件并提取标签，生成 index.json。

用法:
  python build_index.py <根目录>

示例:
  python build_index.py ./docs

生成的 index.json、index.inline.js 与脚本写入的根目录同级（即你传入的那个目录）。
index.inline.js 内含 window.__KB_INDEX__，供 file:// 打开 index.html 时加载索引（浏览器常禁止 fetch 本地 json）。
正文 .md/.html 仍建议用本地 HTTP 服务打开，否则部分浏览器无法 fetch 正文。
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


def parse_md_tags(text: str) -> list[str]:
    """从 Markdown 正文前 10 行内解析独立一行的 tags: 标签1, 标签2"""
    lines = text.splitlines()
    prefix = "tags:"
    for line in lines[:10]:
        s = line.strip()
        low = s.lower()
        if low.startswith(prefix):
            rest = s[len(prefix) :].strip()
            parts = [p.strip() for p in rest.split(",")]
            return [p for p in parts if p]
    return []


_HTML_TAGS_RE = re.compile(
    r"<!--\s*tags:\s*([^>]*?)\s*-->",
    re.IGNORECASE | re.DOTALL,
)


def parse_html_tags(text: str) -> list[str]:
    """从 HTML 前部解析 <!-- tags: 标签1, 标签2 -->（在文件开头一段内搜索）"""
    chunk = text[:16384] if len(text) > 16384 else text
    m = _HTML_TAGS_RE.search(chunk)
    if not m:
        return []
    inner = m.group(1).strip()
    parts = [p.strip() for p in inner.split(",")]
    return [p for p in parts if p]


def read_text_safe(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        try:
            return path.read_text(encoding="utf-8-sig")
        except Exception:
            return ""
    except OSError:
        return ""


def posix_rel(root: Path, file_path: Path) -> str:
    try:
        rel = file_path.relative_to(root)
    except ValueError:
        rel = file_path
    return rel.as_posix()


def build_index(root: Path) -> dict:
    root = root.resolve()
    if not root.is_dir():
        raise NotADirectoryError(f"不是有效目录: {root}")

    folders_out: list[dict] = []

    # 仅一级子目录（按名称排序，保证稳定输出）
    try:
        subdirs = sorted(
            [p for p in root.iterdir() if p.is_dir()],
            key=lambda p: p.name.lower(),
        )
    except OSError as e:
        raise RuntimeError(f"无法读取目录: {root}") from e

    for folder in subdirs:
        name = folder.name
        files_out: list[dict] = []
        try:
            candidates = sorted(
                [p for p in folder.rglob("*") if p.is_file() and p.suffix.lower() in (".md", ".html")],
                key=lambda p: str(p).lower(),
            )
        except OSError:
            candidates = []

        for fp in candidates:
            rel = posix_rel(root, fp)
            tags: list[str] = []
            body = read_text_safe(fp)
            suf = fp.suffix.lower()
            if suf == ".md":
                tags = parse_md_tags(body)
            elif suf == ".html":
                tags = parse_html_tags(body)

            files_out.append(
                {
                    "name": fp.name,
                    "path": rel,
                    "tags": tags,
                }
            )

        folders_out.append({"name": name, "files": files_out})

    return {"folders": folders_out}


def main() -> int:
    parser = argparse.ArgumentParser(
        description="为静态知识库生成 index.json（一级文件夹 + md/html + 标签）"
    )
    parser.add_argument(
        "root",
        type=str,
        help="知识库根目录（其下一级子文件夹为分类）",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=str,
        default=None,
        help="输出 JSON 路径（默认：<根目录>/index.json）",
    )
    args = parser.parse_args()
    root = Path(args.root)
    out_path = Path(args.output) if args.output else root / "index.json"

    try:
        data = build_index(root)
    except Exception as e:
        print(f"错误: {e}", file=sys.stderr)
        return 1

    try:
        out_path.parent.mkdir(parents=True, exist_ok=True)
        json_text = json.dumps(data, ensure_ascii=False, indent=2) + "\n"
        out_path.write_text(json_text, encoding="utf-8")
    except OSError as e:
        print(f"无法写入 {out_path}: {e}", file=sys.stderr)
        return 1

    inline_path = out_path.parent / (out_path.stem + ".inline.js")
    try:
        inline_body = json.dumps(data, ensure_ascii=False, separators=(",", ":"))
        inline_path.write_text(
            "/* auto-generated by build_index.py */\n"
            "window.__KB_INDEX__ = "
            + inline_body
            + ";\n",
            encoding="utf-8",
        )
    except OSError as e:
        print(f"无法写入 {inline_path}: {e}", file=sys.stderr)
        return 1

    print(f"已写入: {out_path.resolve()}")
    print(f"已写入: {inline_path.resolve()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
